"""Minimal stub for optional azure-identity AAD auth."""

from typing import Any

class DefaultAzureCredential:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def get_token(self, *scopes: str, **kwargs: Any) -> Any: ...
    async def close(self) -> None: ...
